/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.6.0-263
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    CallParams,
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v2';


// Services

export interface HelloDef {
    greet: (callParams: CallParams<null>) => string | Promise<string>;
}
export function registerHello(service: HelloDef): void;
export function registerHello(serviceId: string, service: HelloDef): void;
export function registerHello(peer: FluencePeer, service: HelloDef): void;
export function registerHello(peer: FluencePeer, serviceId: string, service: HelloDef): void;
       

export function registerHello(...args: any) {
    registerService(
        args,
        {
    "defaultServiceId" : "hello",
    "functions" : [
        {
            "functionName" : "greet",
            "argDefs" : [
            ],
            "returnType" : {
                "tag" : "primitive"
            }
        }
    ]
}
    );
}
      
// Functions

